### ISSUE TITLE
Movement 2

### ISSUE THREAD

**Issue by grafbrueckner** [simonstehle/DroneRace2.1#2]
![image](https://cloud.githubusercontent.com/assets/20474269/17832576/a1c8f338-6706-11e6-83c0-8a93cb9afade.png)

Hält man nach der Vorwärts-Beschleunigung die Rückwärts-Taste beschleunigt die Drohne ubache schnell. Wenn man den "Respawn" weglässt landet man sogar außerhalb des Stadions.

**Comment by grafbrueckner** [comment]
--> führt zum Crash

**Comment by theMarci658** [comment]
Wie besprochen, ist gefixt
